### ISSUE TITLE
Localized names for well-known groups (e.g. "Administrators") aren't implemented

### ISSUE THREAD

**Issue by ClementNotin** [GhostPack/Seatbelt#1]
Windows has localized names for well-known groups in some locales (for example French or German).
The "Local Group Memberships" section does not implement those and therefore fails on such localized Windows versions.

**Comment by HarmJ0y** [comment]
Should be resolved with https://github.com/GhostPack/Seatbelt/commit/5b3e69c16cc1668622a0e666162b35cb9f7243ca , reopen if it's still failing.

**Comment by ClementNotin** [comment]
Fix confirmed (caught the shout-out :wink:)!
Suggested improvement in #11
