### ISSUE TITLE
Does not build on VS2013

### ISSUE THREAD

**Issue by Zer0-Tolerance** [GhostPack/Seatbelt#13]
Probably an issue with the reference ?
 
Error	1	Type byte, sbyte, short, ushort, int, uint, long, or ulong expected	E:\pentest\Seatbelt\Seatbelt\Program.cs	62	42	Seatbelt
Error	2	Type byte, sbyte, short, ushort, int, uint, long, or ulong expected	E:\pentest\Seatbelt\Seatbelt\Program.cs	81	47	Seatbelt
Error	3	Type byte, sbyte, short, ushort, int, uint, long, or ulong expected	E:\pentest\Seatbelt\Seatbelt\Program.cs	805	50	Seatbelt
Error	4	Type byte, sbyte, short, ushort, int, uint, long, or ulong expected	E:\pentest\Seatbelt\Seatbelt\Program.cs	841	44	Seatbelt
Error	5	Type byte, sbyte, short, ushort, int, uint, long, or ulong expected	E:\pentest\Seatbelt\Seatbelt\Program.cs	871	43	Seatbelt
Error	6	Type byte, sbyte, short, ushort, int, uint, long, or ulong expected	E:\pentest\Seatbelt\Seatbelt\Program.cs	886	41	Seatbelt
Error	7	{ expected	E:\pentest\Seatbelt\Seatbelt\Program.cs	4319	44	Seatbelt
Error	8	; expected	E:\pentest\Seatbelt\Seatbelt\Program.cs	4319	100	Seatbelt
Error	9	} expected	E:\pentest\Seatbelt\Seatbelt\Program.cs	4322	14	Seatbelt
Error	10	The name 'when' does not exist in the current context	E:\pentest\Seatbelt\Seatbelt\Program.cs	4319	44	Seatbelt

**Comment by leechristensen** [comment]
Visual Studio Community 2017 is the supported build environment.  If you determine why VS2013 doesn't build, feel free to submit a PR.
