### ISSUE TITLE
Unhandled exception for extremely long file names

### ISSUE THREAD

**Issue by infosecconsultant** [GhostPack/Seatbelt#21]
When running seatbelt.exe all on a machine it consistently errored out when encountering file names that were at the maximum permissible length in windows.

The following error was thrown

> Unhandled Exception: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
>    at System.IO.Path.SafeSetStackPointerValue(Char* buffer, Int32 index, Char value)
>    at System.IO.Path.NormalizePathFast(String path, Boolean fullCheck)
>    at System.IO.File.GetLastAccessTimeUtc(String path)
>    at Seatbelt.Program.ListInterestingFiles()
>    at Seatbelt.Program.Main(String[] args)

If the program can skip (and maybe count how many files are skipped) without crashing that would be desirable behavior.  Alternately, handling the unusually long values and parsing them the same would be ideal.

Using the latest version of Seatbelt and compiled locally. 

Related: https://github.com/GhostPack/Seatbelt/commit/def4ef3d75d6f28b3b80d3a37b97425f70f3a715
https://github.com/GhostPack/Seatbelt/issues/9

Thanks,

**Comment by marian-trizuliak** [comment]
can be solved by:
1. adding
if (file.ToString().Length > 248)
{
     Console.WriteLine ("Error: File path or filename {0} too long.", file);
}
else
{
     ... 
|

2. Catching exception....

3. Find a way how to bend over the library function accepting long path and file names. Microsoft stupid stuff,

Personally fo rme - I added if else to be able to use the app for the most fucntions (last files not important for my purpose....).

**Comment by leechristensen** [comment]
This should be handled more cleanly with the latest version. Let us know if that's not the case. Thanks!
