### ISSUE TITLE
Seatbelt.exe not executed through Invoke-ReflectedPSInject (What am I missing to the puzzle?)

### ISSUE THREAD

**Issue by minkione** [GhostPack/Seatbelt#23]
**Prologue:**
- Compiled seatbelt in a win10 +VS community (no AV, AMSI, etc.)
- The standalone EXE works fine
- Invoke-ReflectedPEInject works fine with a simple calc.exe
- With Seatbelt.exe I get the following errors with both versions of powershell.exe (32/64bit)

![image](https://user-images.githubusercontent.com/25242404/74934048-ff12d400-53ed-11ea-8a4d-068e8666c311.png)
![image](https://user-images.githubusercontent.com/25242404/74934056-02a65b00-53ee-11ea-891e-cb970a0d9309.png)

**Comment by felixguerrero12** [comment]
Modify class Program to be Public and also change Main to be Public.
https://github.com/GhostPack/Seatbelt/blob/master/Seatbelt/Program.cs#L155
Change from "class Program" to "Public class Program". 

https://github.com/GhostPack/Seatbelt/blob/master/Seatbelt/Program.cs#L6817
Change from "static void Main(string[] args)" to "Public static void Main(string[] args)"

**Comment by leechristensen** [comment]
This is not a Seatbelt issue, as such I am closing it.  There's a variety of ways you could load it in memory. Consider using a [Donut](https://github.com/TheWover/donut)-esque technique or the [Assembly::Load](https://github.com/GhostPack/Rubeus#sidenote-running-rubeus-through-powershell) .NET method
