### ISSUE TITLE
Link in Readme.md points to outdated Visual Studio Community Edition

### ISSUE THREAD

**Issue by Danielg75** [GhostPack/Seatbelt#24]
The link in Readme.md below **Compile Instructions** points to Visual Studio Community Edition version 2015, this does not recognize the used version C# 8.0 in config. It will throw the error "CS1617  C# Invalid option for /langversion" as it only recognizes version 1 through 6.

I would recommend linking to https://visualstudio.microsoft.com/downloads/, this gives the option for Visual Studio 2019.

**Comment by leechristensen** [comment]
Fixed. Thanks for the catch!
