### ISSUE TITLE
Is It Possible To Run On System Without .NET Framework 3.5 Installed

### ISSUE THREAD

**Issue by antonbsi** [GhostPack/Seatbelt#27]
I was wondering if it was possible to run this complied .exe binary on a Windows system which doesnt have .NET 3.5 framework installed. My inital thoughts is no but just wanted to reach out for a definitive answer.

**Comment by HarmJ0y** [comment]
A .NET 3.5 compiled binary will not run on a system that doesn't have .NET 3.5 installed.

We have default build version for the project set at 3.5 to ensure backwards compatibility, but it builds perfectly fine with 4.X. If you right click the Seatbelt project and go to properties, you can retarget the solution for 4.X versions and rebuild a binary that will work for 4.X:

![image](https://user-images.githubusercontent.com/5504523/83550569-e5d4f580-a4bb-11ea-90f3-5f4b061612ef.png)

**Comment by antonbsi** [comment]
Perfect, that worked a treat 👍
