### ISSUE TITLE
Environment.Exit() is bad

### ISSUE THREAD

**Issue by rasta-mouse** [GhostPack/Seatbelt#35]
**Describe the bug**

Maybe not fair to call this a bug, but Seatbelt calls `Environment.Exit()` here:
https://github.com/GhostPack/Seatbelt/blob/master/Seatbelt/Runtime.cs#L77

When Seatbelt is being run via (or integrated into) a tool/implant like Covenant's Grunt that runs the assembly within the implant's process (i.e. no fork & run) - it will cause the whole implant to exit when this exception is caught.

It would be nicer to orchestrate a way of gracefully returning so we can drop out of the assembly without explicitly calling this exit method.

**To Reproduce**

1. Start a Grunt.
2. Run Seatbelt with some remote enumeration options that will fail, e.g: `Seatbelt -group=remote -computername=something.local -username=DOMAIN\fake -password=DoesNotMatter`.
3. Watch the Grunt exit.

**Comment by leechristensen** [comment]
Thanks! Fixing in #36

**Comment by HarmJ0y** [comment]
Reviewed and landed into master. Thanks @rasta-mouse !

**Comment by rasta-mouse** [comment]
Thanks for the awesome turn around time guys <3
