### ISSUE TITLE
To enumerate a remote system, supply -computername=COMPUTER.DOMAIN.COM - an alternate username and password can be specified with -username=DOMAIN\USER -password=PASSWORD  For example, the following command runs remote-focused checks against a remote system:  Seatbelt.exe -group=remote -computername=192.168.230.209 -username=THESHIRE\sam -password="yum \"po-ta-toes\""

### ISSUE THREAD

**Issue by 127161782** [GhostPack/Seatbelt#43]
username是字符串吗？还是路径？
password的问题一样。

**Comment by HarmJ0y** [comment]
Doesn't follow the issue template, not 100% sure what the issue even is.

**Comment by 127161782** [comment]
我的问题是：访问远程目标为192.168.101.39，用户名为123，密码为123。我的命令为：seatbelt -group =remote 
 -computername=192.168.101.39 -username='123' -password='123' 
运行报错：拒绝访问，（异常来自 HRESULT：0X80070005（E_ACCESSDENIED）)

**Comment by HarmJ0y** [comment]
I'm not sure if the remote options work with local accounts (I haven't tested it). If this is a domain connected system, try using DOMAIN\USER for the username as documented at https://github.com/GhostPack/Seatbelt#remote-enumeration

The code to run remote enumeration is implemented at https://github.com/GhostPack/Seatbelt/blob/9b22b5fec9aa92fd26f1db10ae7a1ad516ad29b8/Seatbelt/Runtime.cs#L56-L62 . So my best guess is that either a) you forgot a domain name, b) the credentials are incorrect, or c) the WMI connection approach might not work with local accounts.

Best of luck.
