### ISSUE TITLE
Compile error on .NET 4.5

### ISSUE THREAD

**Issue by dirkjanm** [GhostPack/Seatbelt#59]
MSBuild complains when I try to compile latest version from git in .net 4.5:

```
  Commands\Misc\LOLBAS.cs(130,27): error CS8618: Non-nullable property 'Path' is uninitialized. Consider declaring the property as nullable. [D:\a\1\s\Seatbelt\Seatbelt.csproj]
```

Without the LOLBAS module it compiles fine. Probably not that hard to fix but I don't have a VS env and git setup nearby to test and create a PR. Thx for the work on this!

**Comment by Flangvik** [comment]
Can confirm, having the same issue

**Comment by leechristensen** [comment]
Fixed in #58 , just waiting for a merge

**Comment by HarmJ0y** [comment]
Should be landed to master now, closing.

**Comment by dirkjanm** [comment]
Can confirm it compiles fine now, thanks for the quick fix!
