### ISSUE TITLE
The arguments "all" and "full" cannot be combined

### ISSUE THREAD

**Issue by ClementNotin** [GhostPack/Seatbelt#7]
The README states that:
> SeatBelt.exe all will run ALL enumeration checks, can be combined with full.

And the blog post states that:
> SeatBelt.exe [system/user/all/CheckName] full will prevent any filtering and will return complete results.

However something seems wrong with the arguments parsing since neither `Seatbelt.exe all full` nor `Seatbelt.exe full all` work. Both generate the `Check "all" not found!` error.

**Comment by HarmJ0y** [comment]
Should be resolved with https://github.com/GhostPack/Seatbelt/commit/5b3e69c16cc1668622a0e666162b35cb9f7243ca , reopen if it's still failing.

**Comment by ClementNotin** [comment]
Fix confirmed!
