### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by FabioDefilippo** [GhostPack/Seatbelt#87]
Please, could You release a x86 and x86-64 version? Thank You

**Comment by PinkDev1** [comment]
Since GhostPack said "We are not planning on releasing binaries for Seatbelt, so you will have to compile yourself." on the README, I made this: https://github.com/PinkDev1/Seatbelt-Releases

**Comment by FabioDefilippo** [comment]
thank you.
even if I have read it in README, I have asked to GhostPack anyway

**Comment by leechristensen** [comment]
Like the README states, we're not going to create binaries. We'll leave custom compilation and output formats to you.
