### ISSUE TITLE
ChromiumHistory: IO exception, history file likely in use

### ISSUE THREAD

**Issue by tmalgherini** [GhostPack/Seatbelt#89]
When running the ChromiumHistory command i get the following error: 
`ERROR: IO exception, history file likely in use (i.e. browser is likely running): The process cannot access the file ...`

This line is where it fails:
https://github.com/GhostPack/Seatbelt/blob/fa0f2d94a049d825bef77e103e33167250ed2ac0/Seatbelt/Commands/Browser/ChromiumHistoryCommand.cs#L57
I've replaced it with the following lines, and it seems to have fixed it, i can now extract history while the browser is running (tested with Chrome, Edge and Brave, all latest versions):
```
using (var fs = new FileStream(userChromiumHistoryPath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
using (var r = new StreamReader(fs)){ ...
```

**Comment by leechristensen** [comment]
Fixed in #101 .   Thanks for letting me know the fix that worked!
