### ISSUE TITLE
Non-nullable property 'Path' must contain a non-null value when exiting constructor.

### ISSUE THREAD

**Issue by lnaphade** [GhostPack/Seatbelt#91]
Build started...
1>------ Build started: Project: Seatbelt, Configuration: Debug Any CPU ------
1>C:\Users\Lalit\Source\Repos\Seatbelt\Seatbelt\Commands\Misc\LOLBAS.cs(130,27,130,31): error CS8618: Non-nullable property 'Path' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

   WriteVerbose($"Found: {query.Count()} LOLBAS");
            WriteHost("\nTo see how to use the LOLBAS that were found go to https://lolbas-project.github.io/");
        }

        internal class LolbasDTO : CommandDTOBase
        {
**line 130:**          public string Path { get; set; }

**Comment by leechristensen** [comment]
Are you using the latest version of Seatbelt from Github? The LOLBAS constructor initializes that value in the current code. See 
https://github.com/GhostPack/Seatbelt/blob/master/Seatbelt/Commands/Misc/LOLBAS.cs#L128-L135
